### ISSUE TITLE
Does it support sending Card UUI over MQTT by default

### ISSUE THREAD

**Issue by HobbytronicsPK** [esprfid/esp-rfid#264]
Hello,

We need to read UUID of 13.56MHz RFID Card using MFRC522 and send it over MQTT. Does your software implement it by default? Because there is an MQTT support builtin there.

**Comment by omersiar** [comment]
Yes.

https://github.com/esprfid/esp-rfid/blob/stable/src/mqtt.esp#L78-L97

It sends Unix Time Stamp, If UID is known or not, Card Type, User Name (if applicable), UID 

as JSON formatted text
